Functions Refactor Runtimes
appwrite/runtimes pull request #31
Opened 2021-12-07 13:33 UTC by PineappleIOnic

This PR contains all the new rewritten runtimes, tests and documentation for the new runtime style defined within the runtimes refactor RFC seen here: https://github.com/appwrite/rfc/pull/29 for the new functions refactor.

Notes: Currently we are missing both the Java runtime and the Swift runtime since they are still currently being worked on.

2022-01-16 13:03 UTC, lohanidamodar requested changes
Went through the Dart runtimes and left some feedback.

2022-01-16 13:03 UTC, lohanidamodar commented on runtimes/dart-2.13/.packages
> +# This file is deprecated. Tools should instead consume
This file should be ignored in git

2022-01-16 13:03 UTC, lohanidamodar commented on runtimes/dart-2.13/README.md
> +User Dependencies are not currently supported. This is a planned feature.
Let's update this, user dependencies are supported right? we build user's code get their dependencies during build?

2022-01-16 13:03 UTC, lohanidamodar commented on runtimes/dart-2.13/appwrite_function_types/lib/appwrite_function_types.dart
> +import 'dart:convert';
These function types for dart and type definition for other languages should be published, as developers will have to use it in their code. Let's discuss this.

2022-01-16 13:03 UTC, lohanidamodar commented on runtimes/dart-2.14/user_code/analysis_options.yaml
> +# Defines a default set of lint rules enforced for projects at Google. For
We should add Dart 2.15 as well.

2022-01-18 15:38 UTC, PineappleIOnic commented on README.md
> +**WARNING:** On MacOS and Windows the `/tmp/builtCode/` needs to be created before the tests are run. This is due to a wierd permission issue on Docker Desktop that occours if the directory does not
Good Catch, not really sure how I should translate that into windows. I've never really ran tests on windows before.

Maybe we shouldn't mention windows?

2022-01-18 15:39 UTC, PineappleIOnic commented on runtimes/dart-2.12/README.md
> +User Dependencies are not currently supported. This is a planned feature.
This has been fix with the new dart readmes

2022-01-18 15:41 UTC, PineappleIOnic commented on runtimes/dart-2.12/pubspec.yaml.fallback
> +name: appwrite_dart_function
The fallback file? or the name?

2022-06-09 12:28 UTC, PineappleIOnic commented
This PR will be closed as these runtimes have been merged into OpenRuntimes

2022-06-09 12:28 UTC, closed without merging