Refactor php fixes
appwrite/runtimes pull request #37
Opened 2022-02-01 11:05 UTC by TorstenDittmann

2022-02-15 15:04 UTC, PineappleIOnic commented
Should these changes be moved over to the openruntimes project?

2022-06-09 04:36 UTC, lohanidamodar commented
@TorstenDittmann  is this still relevant?

2022-11-02 15:31 UTC, stnguyen90 commented
@TorstenDittmann, looks like there are merge conflicts now.

2023-03-21 07:47 UTC, lohanidamodar requested changes
I don't think this is relevant any longer

2023-10-18 09:43 UTC, closed without merging